# Generated by Django 4.2.2 on 2023-06-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNumber', models.IntegerField(default=0)),
                ('secondNumber', models.IntegerField(default=0)),
                ('mathType', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
