# Generated by Django 4.2.2 on 2023-06-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='answer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
